---
repos:
  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://github.com/timothycrosley/isort
    rev: 'master'
    hooks:
      - id: isort
        additional_dependencies: ['toml']

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/pycqa/pydocstyle
    rev: master
    hooks:
      - id: pydocstyle


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v2.3.0'
    hooks:
      # Run flake8
      - id: flake8
        additional_dependencies: [
          flake8-docstrings,
          flake8-builtins,
          flake8-quotes,
          flake8-bugbear,
        ]
      # Prevent giant files from being committed
      - id: check-added-large-files
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Ensure that (non-binary) executables have a shebang
      - id: check-executables-have-shebangs
      # Check json files for parseable syntax
      - id: check-json
      # Set a standard for formatting JSON files
      # - id: pretty-format-json
      # Check for symlinks which do not point to anything
      - id: check-symlinks
      # Check yaml files for parseable syntax
      - id: check-yaml
      # This hook checks toml files for parseable syntax.
      - id: check-toml
      # Detects the presence of private keys
      - id: detect-private-key
      # Replace double quoted strings with single quoted strings
      # - id: double-quote-string-fixer
      # Ensure that a file is either empty, or ends with one newline
      - id: end-of-file-fixer
      # Trim trailing whitespace
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master
    hooks:
      # Shell scripts conform to shellcheck
      - id: shellcheck
      # Non-executable shell script filename ends in .sh
      - id: script-must-have-extension
      # Executable shell script omits the filename extension
      - id: script-must-not-have-extension
