[tool.poetry]
name = "my-ip"
version = "0.1.0"
description = ""
authors = ["lainiwa <kirrik96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = {version = "^3.6", extras = ["speedups"]}
toml = "^0.10.0"
pydantic = "^0.32.2"
click = "^7.0"
[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
mip = 'my_ip.console:cli'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

